// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: audio.proto

package audio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	AudioStream(ctx context.Context, opts ...grpc.CallOption) (AudioService_AudioStreamClient, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) AudioStream(ctx context.Context, opts ...grpc.CallOption) (AudioService_AudioStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], "/audio.AudioService/AudioStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceAudioStreamClient{stream}
	return x, nil
}

type AudioService_AudioStreamClient interface {
	Send(*AudioEvent) error
	Recv() (*AudioResponseEvent, error)
	grpc.ClientStream
}

type audioServiceAudioStreamClient struct {
	grpc.ClientStream
}

func (x *audioServiceAudioStreamClient) Send(m *AudioEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioServiceAudioStreamClient) Recv() (*AudioResponseEvent, error) {
	m := new(AudioResponseEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility
type AudioServiceServer interface {
	AudioStream(AudioService_AudioStreamServer) error
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServiceServer struct {
}

func (UnimplementedAudioServiceServer) AudioStream(AudioService_AudioStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AudioStream not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_AudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioServiceServer).AudioStream(&audioServiceAudioStreamServer{stream})
}

type AudioService_AudioStreamServer interface {
	Send(*AudioResponseEvent) error
	Recv() (*AudioEvent, error)
	grpc.ServerStream
}

type audioServiceAudioStreamServer struct {
	grpc.ServerStream
}

func (x *audioServiceAudioStreamServer) Send(m *AudioResponseEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioServiceAudioStreamServer) Recv() (*AudioEvent, error) {
	m := new(AudioEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audio.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AudioStream",
			Handler:       _AudioService_AudioStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "audio.proto",
}
